# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.stackedWidget = QtWidgets.QStackedWidget(parent=Form)
        self.stackedWidget.setGeometry(QtCore.QRect(20, 20, 351, 251))
        self.stackedWidget.setObjectName("stackedWidget")
        self.MainPage = QtWidgets.QWidget()
        self.MainPage.setObjectName("MainPage")
        self.submitButton = QtWidgets.QPushButton(parent=self.MainPage)
        self.submitButton.setGeometry(QtCore.QRect(140, 20, 75, 23))
        self.submitButton.setObjectName("submitButton")
        self.stackedWidget.addWidget(self.MainPage)
        self.SubmitPage = QtWidgets.QWidget()
        self.SubmitPage.setObjectName("SubmitPage")
        self.backButton = QtWidgets.QPushButton(parent=self.SubmitPage)
        self.backButton.setGeometry(QtCore.QRect(140, 200, 75, 23))
        self.backButton.setObjectName("backButton")
        self.stackedWidget.addWidget(self.SubmitPage)
        self.exitButton = QtWidgets.QPushButton(parent=Form)
        self.exitButton.setGeometry(QtCore.QRect(160, 270, 75, 23))
        self.exitButton.setObjectName("exitButton")

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.submitButton.setText(_translate("Form", "Submit"))
        self.backButton.setText(_translate("Form", "Back"))
        self.exitButton.setText(_translate("Form", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
